apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: modest-whippet-nodejs 
  janus-idp.io/tekton: modest-whippet-nodejs
  backstage.io/kubernetes-id: modest-whippet-nodejs
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: modest-whippet-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  